# System-wide CPAN configuration for Perl 5.18.2 running under perlbrew.

$CPAN::Config = {
    'applypatch'                    => q[],
    'auto_commit'                   => q[1],
    'build_cache'                   => q[256],
    'build_dir'                     => q[/usr/local/perl/cpan/perl-5.18.2/build],
    'build_dir_reuse'               => q[0],
    'build_requires_install_policy' => q[no],
    'bzip2'                         => q[/bin/bzip2],
    'cache_metadata'                => q[1],
    'check_sigs'                    => q[0],
    'colorize_output'               => q[0],
    'commandnumber_in_prompt'       => q[1],
    'connect_to_internet_ok'        => q[1],
    'cpan_home'                     => q[/usr/local/perl/cpan/perl-5.18.2],
    'ftp_passive'                   => q[1],
    'ftp_proxy'                     => q[],
    'getcwd'                        => q[cwd],
    'gpg'                           => q[/usr/bin/gpg],
    'gzip'                          => q[/bin/gzip],
    'halt_on_failure'               => q[0],
    'histfile'                      => q[/usr/local/perl/cpan/perl-5.18.2/histfile],
    'histsize'                      => q[256],
    'http_proxy'                    => q[],
    'inactivity_timeout'            => q[0],
    'index_expire'                  => q[1],
    'inhibit_startup_message'       => q[0],
    'keep_source_where'             => q[/usr/local/perl/cpan/perl-5.18.2/sources],
    'load_module_verbosity'         => q[none],
    'make'                          => q[/usr/bin/make],
    'make_arg'                      => q[-j3],
    'make_install_arg'              => q[UNINST=1],
    'make_install_make_command'     => q[/usr/bin/make],
    'makepl_arg'                    => q[],
    'mbuild_arg'                    => q[],
    'mbuild_install_arg'            => q[--uninst 1],
    'mbuild_install_build_command'  => q[./Build],
    'mbuildpl_arg'                  => q[],
    'no_proxy'                      => q[],
    'pager'                         => q[/usr/bin/sensible-pager],
    'patch'                         => q[/usr/bin/patch],
    'perl5lib_verbosity'            => q[none],
    'prefer_external_tar'           => q[1],
    'prefer_installer'              => q[EUMM],
    'prefs_dir'                     => q[/usr/local/perl/cpan/perl-5.18.2/prefs],
    'prerequisites_policy'          => q[follow],
    'scan_cache'                    => q[atstart],
    'shell'                         => q[/bin/bash],
    'show_unparsable_versions'      => q[0],
    'show_upload_date'              => q[0],
    'show_zero_versions'            => q[0],
    'tar'                           => q[/bin/tar],
    'tar_verbosity'                 => q[v],
    'term_is_latin'                 => q[1],
    'term_ornaments'                => q[1],
    'test_report'                   => q[0],
    'trust_test_report_history'     => q[0],
    'unzip'                         => q[/usr/bin/unzip],
    'urllist'                       => [
        q[http://ftp.hosteurope.de/mirror/www.cpan.org/],
        q[http://ftp.gwdg.de/pub/languages/perl/CPAN/],
    ],
    'use_sqlite'      => q[0],
    'version_timeout' => q[15],
    'wget'            => q[/usr/bin/wget],
    'yaml_load_code'  => q[0],
    'yaml_module'     => q[YAML],
};

1;

__END__
